
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nannyapp4u_development


test:
  <<: *default
  database: nannyapp4u_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: nannyapp4u_production
  username: nannyapp4u
  password: <%= ENV['HELLO-WORLD_DATABASE_PASSWORD'] %>
  database: db/test.sqlite3


